/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView */

#ifndef _Included_mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView
#define _Included_mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView
 * Method:    CollectData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView_CollectData
  (JNIEnv *, jobject);

/*
 * Class:     mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView
 * Method:    Init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView_Init
  (JNIEnv *, jobject, jint);

/*
 * Class:     mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView
 * Method:    UnInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mobi_xjtusei_touchcertifysystemffour_mtcollector_MultiTouchView_UnInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
